import React from 'react';

export default function Head() {
    return (
      <>
        <title>Elkin Rodriguez</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/public/images/artificial-intelligence.png"
        />
      </>
    )
  }